### ISSUE TITLE
运行scipy.py

### ISSUE THREAD

**Issue by mmApr** [ChangYunPeng/VideoAnomalyDetection#1]
运行scipy.py ，报错NameError: name 'model_type' is not defined，想问一下如何解决？

**Comment by HaiderHHMK** [comment]
Traceback (most recent call last):
  File "/home/650183/script.py", line 117, in <module>
    train(args)
  File "/home/650183/script.py", line 32, in train
    solver = Solver(config, cluster_model=PredRes_AE_Cluster_Model,model_type=model_type)
NameError: name 'model_type' is not defined
